# Generated by Django 3.1.3 on 2020-12-01 11:05

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0002_auto_20201112_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='car',
            field=models.CharField(default='Regular car', max_length=255),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='car_image',
            field=models.ImageField(default='hotelsample.jpg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='num_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='other',
            field=models.CharField(default='yes', max_length=225),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.date(2020, 12, 1)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2020, 12, 1)),
        ),
    ]
